### ISSUE TITLE
login

### ISSUE THREAD

**Issue by Shabiul** [pavanpatil45/Auto-Spare-Parts-Management#4]
i have through all 4 login details but I am not able to login can u pls provide the login details

**Comment by 0740471258** [comment]
Did you get login details?

**Comment by Shabiul** [comment]
NO

**Comment by sumeetpatil01** [comment]
Try User name : admin1
       Password: admin1
It will work

**Comment by 0740471258** [comment]
Thank you for your response.

**Comment by alejandroleiter** [comment]
in the processlogin.php remove hash password function and change passwords in spare_parts.sql

**Comment by Shabiul** [comment]
thanks now its working
